name: Publish

on:
  push:
    tags:
     - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  buildAndPack:
    uses: ./.github/workflows/ci.yml
    with:
      artifact-version: ${{ github.ref_name }}

  publish:
    needs: buildAndPack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Brag
        run: echo "I'm built different >:D"
      
      - name: Get built package
        uses: actions/download-artifact@v2
        with:
          name: build-${{ github.ref_name }}

      - name: Push to GitHub Releases
        uses: svenstaro/upload-release-action@v2
        with: 
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.nupkg
          tag: ${{ github.ref }}
          file_glob: 'true'
        
      - name: Push to GitHub NuGet feed
        run: dotnet nuget push *.nupkg 
              --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json 
              --api-key ${{ secrets.GIT_NUGET_TOKEN }}
      
      - name: Push to NuGet Feed
        run: dotnet nuget push *.nupkg
              --source https://api.nuget.org/v3/index.json
              --api-key ${{ secrets.NUGET_TOKEN }}
