name: Build

on:
  workflow_call:
    inputs:
      artifact-version:
        required: false
        type: string

  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test
      
      - name: Pack
        if: inputs.artifact-version
        run: dotnet pack --configuration Release --no-build --output .

      - name: Upload package
        if: inputs.artifact-version
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ inputs.artifact-version }}
          path: './*.nupkg'
          if-no-files-found: error
