on: 
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env: 
      DOTNET_NOLOGO: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2 

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '5.0.402'

    - name: Restore dotnet tools
      run: dotnet tool restore 

    - name: Sanity check
      run: dotnet fake --version